name: agc-py310-uproot5
channels:
  - conda-forge
dependencies:
  - python=3.10 # no numba package compatible with 3.11 in conda-forge at the moment
  - pip
  - pip:
    - fastjsonschema
    - func-adl
    - func-adl-servicex
    - ipython-genutils
      # these extensions are not available in conda-forge but I'm not sure it's a good idea to install them from pip
      #    - jupyter-console
      #    - jupyter-events
      #    - jupyterlab-pygments
      #    - jupyterlab-widgets
    - make-it-sync
    - mplhep-data
    - msgpack
    - notebook_shim
    - prometheus-client
    - pure-eval
    - qastle
    - servicex
    - stack-data
  - aiohttp
  - aiosignal
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-timeout
  - attrs
  - awkward
  - awkward0
  - backcall
  - backoff
  - beautifulsoup4
  - bleach
  - bokeh
  - boost-histogram
  - cabinetry
  - cachetools
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cloudpickle
  - coffea
  - comm
  - configparser
  - confuse
  - contourpy
  - correctionlib
  - cycler
  - dask
  - debugpy
  - decorator
  - defusedxml
  - distributed
  - executing
  - fonttools
  - fqdn
  - frozenlist
  - fsspec
  - google-auth
  - HeapDict
  - hist
  - histoprint
  - idna
  - iminuit
  - importlib-metadata
  - ipykernel
  - ipython
  - ipywidgets
  - isoduration
  - jedi
  - Jinja2
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyterlab
  - jupyter_client
  - jupyter_core
  - jupyter_server
  - jupyter_server_terminals
  - jupytext
  - kiwisolver
  - lark-parser
  - llvmlite
  - locket
  - lz4
  - markdown-it-py
  - MarkupSafe
  - matplotlib
  - matplotlib-inline
  - mdurl
  - minio
  - mistune
  - mplhep
  - multidict
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - notebook
  - numba
  - numpy<1.22 # for coffea
  - packaging
  - pandas
  - pandocfilters
  - parso
  - partd
  - particle
  - pexpect
  - pickleshare
  - Pillow
  - platformdirs
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pydantic
  - Pygments
  - pyhf
  - pyparsing
  - pyrsistent
  - python-dateutil
  - python-json-logger
  - pytz
  - PyYAML
  - pyzmq
  - qtconsole
  - QtPy
  - rfc3339-validator
  - rfc3986-validator
  - rich
  - rsa
  - scipy
  - Send2Trash
  - six
  - sniffio
  - sortedcontainers
  - soupsieve
  - tabulate
  - tblib
  - terminado
  - tinycss2
  - toml
  - toolz
  - tornado
  - tqdm
  - traitlets
  - tritonclient
  - typing_extensions
  - uhi
  - uproot=5
  - uproot3
  - uproot3-methods
  - uri-template
  - urllib3
  - vector
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - widgetsnbextension
  - xgboost
  - yarl
  - zict
  - zipp
  - zstandard
  - scikit-learn
